Adding functionality to expose Dual Values
rust-or/good_lp pull request #2
Opened 2021-03-03 22:51 UTC by dandxy89

As per your suggestion on Reddit I had a stab at implementing the functionality to expose dual values.

2021-03-03 22:51 UTC, dandxy89 commented
Also includes some minor formatting - VSCode seems eagar!

2021-03-04 08:38 UTC, lovasoa requested changes
Thank you very much ! I added my remarks below.
The failing tests highlight a serious memory error, we need to investigate that.

2021-03-04 08:38 UTC, lovasoa commented on src/dual.rs
> +}
I don't think the trait should work like that. This forces either the solver's internal representation to always have the dual values as a continuous slice of doubles, or us to always compute the dual values when we don't need them. 

I think the trait should allow code to look like the following : 

```rust
let my_constraint : ConstraintReference = pb.add_constraint( x + y << 7)
let solution = pb.solve()?
let constraint_dual =  solution.get_dual().value(my_constraint)
```

This means : 
  - creating `add_constraint(&mut self, Constraint) -> ConstraintReference`
  - creating a `SolutionWithDual` which allows computing the dual values, and a `DualValues` trait (or just a struct) that takes a  `ConstraintReference` and returns the corresponding dual value.

2021-03-04 08:38 UTC, lovasoa commented on tests/shadow_price.rs
> +#[allow(clippy::float_cmp)]
Not a good idea 😬 . We already have float_eq in the devdependencies, you should use that: https://docs.rs/float_eq/0.5.0/float_eq/macro.assert_float_eq.html

2021-03-04 08:38 UTC, lovasoa commented on tests/solver_scaling.rs
> +#[allow(clippy::needless_range_loop)]
Clippy was right, we should change the loop to `v.iter().enumerate()`

2021-03-04 08:51 UTC, lovasoa commented
I reported the memory corruption to https://github.com/KardinalAI/coin_cbc/issues/9

2021-03-04 09:42 UTC, lovasoa commented on tests/shadow_price.rs
> +        assert_float_eq!(40.00000000000001, solution.value(n_tables), abs <= 1e-10);
This should probably be 30.0 and 40.0 instead. You can reduce the abs if necessary

2021-03-04 09:43 UTC, lovasoa commented on tests/shadow_price.rs
> +        assert_float_eq!(6.485084306095981, solution.value(x2), abs <= 1e-10);
Can we choose a problem with more "round" solutions ? These are easier to check.

2021-03-04 09:43 UTC, lovasoa commented on tests/shadow_price.rs
> +            -15.000000000000004,
15

2021-03-04 09:43 UTC, lovasoa commented on tests/shadow_price.rs
> +        assert_float_eq!(-4.999999999999992, solution.get_dual_value(1), abs <= 1e-10);
5

2021-03-04 11:46 UTC, dandxy89 commented
@lovasoa had a stab at implementing your initial suggestions. It works but I suspect you've got a better handle of Rust than me...

Comments about rounding and probelm are valid - will update once you're happy with the actual solution for dual variables.

2021-03-04 11:57 UTC, lovasoa requested changes

2021-03-04 11:57 UTC, lovasoa commented on src/solvers/minilp.rs
> +    }
We probably shouldn't duplicate code between `add_constraint` and `with`. We can have a default method implementation in `SolverModel` for with that internally uses add_constraint.

2021-03-04 13:35 UTC, lovasoa requested changes

2021-03-04 13:35 UTC, lovasoa commented on src/solvers/mod.rs
> +    fn get_dual_value(&self, c: ConstraintReference) -> f64;
If the underlying solver only offers a function to compute all dual variables together, this forces to allocate an array for all the dual results, and then throw away everything but the variable you are interested in.

What I was suggesting was something that would let you write

```
let constraint_dual : f64 =  solution.get_dual().value(my_constraint)
```

That is, first compute all the dual values, then extract the one you are interested in.

```rust
```

2021-03-04 18:25 UTC, dandxy89 commented
@lovasoa had another go at attempting to implement what you've advised. 

I feel it could be better but I think I'm reaching my _current knowledge boundary_ of Rust...Happy for you to jump in a re-work. 

Keen to learn!

2021-03-17 19:43 UTC, dandxy89 commented
@lovasoa do you have an opportunity to review and provide guidance?

2021-03-19 08:51 UTC, lovasoa commented
Hello ! Sorry, I have been a little busy, but I'm going to look into this today !

2021-03-19 11:16 UTC, lovasoa commented
@dandxy89 : I made the changes I wanted. If it looks good to you, I'll merge and publish a new version.

2021-03-19 12:24 UTC, dandxy89 reviewed
Awesome. Thanks @lovasoa

2021-03-19 14:19 UTC, merged

2021-03-19 16:18 UTC, lovasoa commented
Published as 0.4.

Would you like to be added to the rust-or org ?

2021-03-19 16:39 UTC, dandxy89 commented
@lovasoa sure.